### ISSUE TITLE
Tools, Datasets, and Standards

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-documentation#20]
@matentzn has written a beautiful page collecting the tools, datasets, and standards maintained/contributed to by the monarch initiative 

this issue proposes a slight restructuring, separating out each section into its own tab (while also eliminating any potential redundancies)

**Comment by glass-ships** [comment]
Hey, @matentzn would you be able to elaborate a little on the structure of the `src/data/resource.yaml` file? 

I notice there's a tools and separate repository section, and there's only some overlap between the two. 
What is the distinction between / intention of these two sections?

**Comment by glass-ships** [comment]
I think the term "Tools" [developed/contributed to by Monarch] vs "Repositories [maintained by Monarch" is a more clear as an abstraction, and I think using that as a label makes sense 

Mostly I just wonder about the contents, I noticed some repos under Tools that weren't in the larger Repositories list. 

I guess my question is really, do we want to  
- organize the greater list of tools(by organization, function, "closeness" to the monarch kg, etc.), 
- just list out every tool developed/contributed to by the monarch initiative and its collaborators 
- or separate them into different sections based on... i don't know, something?

**Comment by matentzn** [comment]
I think the goal should be to list all tools/standards/assets which for which Monarch is among the primary responsible organisations. For most cases this will be very clear, for others, like GH4GH, FHIR etc it may be a bit harder to define. So the closeness, which I tried to capture with the `monarch_contributes` slot (`lead`, etc) will probably be the main organising principle after the type (tool, dataasset, standard, etc).

**Comment by glass-ships** [comment]
I had a few questions regarding this, I figure instead of creating a new issue, this one makes sense for discussion. 

- Is the list containing all monarch/monarch adjacent tools complete? 
- How do we want to categorize / organize that list
- Is the "closeness" feature you suggest something that can be gleaned from some GitHub API data? Or will we need someone familiar with the entire infrastructure to manually sort them
- The list of "Tools" should effectively replace the existing "Repositories" section, correct?

**Comment by matentzn** [comment]
> Is the list containing all monarch/monarch adjacent tools complete?

No, not even close. I just made a list in 20 minutes of the things I could think of top of my head. Neads others to chime in.

> How do we want to categorize / organize that list

You mean the YAML file? Its just a database, I was just going to list all tools right underneath each other and do the organisation on the side of the display: https://monarch-initiative.github.io/monarch-technical-documentation/registry/

> Is the "closeness" feature you suggest something that can be gleaned from some GitHub API data? Or will we need someone familiar with the entire infrastructure to manually sort them

No, I was going to manually curate categories like "lead", "co-lead", "contributor"..

> The list of "Tools" should effectively replace the existing "Repositories" section, correct?

I personally think so!

**Comment by glass-ships** [comment]
this seems done. feel free to re-open if that's not the case
