### ISSUE TITLE
Add an SOP on how to add a new Page to the documentation

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/monarch-documentation#37]
The current setup is very confusing - half the pages do not update automatically, and I cant see how to add a manual page without digging deep. 

@glass-ships can you explain 

1. How to add a new, manually curated page (to TOC as well)
2. Edit the TOC manually

**Comment by glass-ships** [comment]
this is an unfortunate side effect of our decision to use the linkml project cookiecutter (which to be honest was probably not entirely necessary)

i'll look at getting this added in #36

**Comment by matentzn** [comment]
Thanks! We also need to make sure that _all_ pages are being updated.

**Comment by glass-ships** [comment]
all pages should be updated by running `make build-docs`

also what are you referring to when you say table of contents? as far as i know, there isn't one for these docs

**Comment by matentzn** [comment]
I mean this: 
![image](https://github.com/monarch-initiative/monarch-documentation/assets/7070631/5f951f42-8ef0-478e-8abd-51bb60a857f0)

**Comment by glass-ships** [comment]
https://github.com/monarch-initiative/monarch-documentation/tree/add-release-doc#add-new-documentation

**Comment by matentzn** [comment]
Sweet, thank you @glass-ships!
