### ISSUE TITLE
Clarify content in resources.yaml

### ISSUE THREAD

**Issue by glass-ships** [monarch-initiative/monarch-documentation#39]
Blocker to https://github.com/monarch-initiative/monarch-app/pull/463

It would be helpful to understand what is in this file and how it is organized. 

For example:
- [X] what do we define as "standards"
- [X] what differentiates "data" from "ontologies"
- [ ] how are we separating tools from repositories
- [X] what is the point of the documentations section, when the documentation field exists for entries in the other sections? 
- [X] anything else to make maintaining this beast of a file (and using it in such cases as generating the resources page for the website) easier

**Comment by matentzn** [comment]
Thank you for this issue. In #40 I have:

1.  Defined all sections (standards, tools, data, ontologies)
2. Removed everything from the documentation section that is not _just_ documentation (leaving two items). The website uses the other fields now to generate the overview page.
3. I generated the overview of the file you need now automatically and deposit it as part of the documentation (`docs/resources/monarch_app_resources.json`).

What is still missing is

> how are we separating tools from repositories

Right now they are redundant, but in a future push we should get rid of the "repository" section altogether and let it be driven entirely by the rest of the system.
