### ISSUE TITLE
Update Monarch Ingest Tutorial

### ISSUE THREAD

**Issue by victoriasoesanto** [monarch-initiative/monarch-documentation#57]
1. Update output file: poetry run koza transform --global-table monarch_ingest/translation_table.yaml --source monarch_ingest/pombase/metadata.yaml --output-format tsv (Output file is no longer metadata.yaml)
2. Update validation output: poetry run kgx validate -i tsv output/PomBase.gene-to-phenotype_nodes.tsv output/PomBase.gene-to-phenotype_edges.tsv (Output file no longer have '.' and '-' is replaced with '_')

**Comment by monicacecilia** [comment]
Hello @glass-ships - could I kindly ask if you can take a look at the feasibility and need for this ticket? 
It might be the case that documentation has already advanced past the needs described here. If so, please note it here and we can close. 
Else, let's figure out the next step. Thank you!

**Comment by glass-ships** [comment]
Thanks Moni! Yeah this is outdated info that isn't relevant to how monarch-ingest works now (has its own command line interface and is documented here: https://monarch-initiative.github.io/monarch-ingest)
