### ISSUE TITLE
Merge Monarch Ingest documentation into Monarch Documentation

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-documentation#58]
The [Monarch Ingest Documentation](https://monarch-initiative.github.io/monarch-ingest/) should either be linked from or merged into the [Monarch Documentation](https://monarch-initiative.github.io/monarch-documentation/) pages. 
I would prefer for this to all be on a single site, the latter. However, I'm willing to entertain alternatives as needed to make everyone's lives easier. 
Thank you! 🌷 

@matentzn 👀 👆🏽

**Comment by matentzn** [comment]
I think either way is fine. I have a mild preference to "linked" (keep separate docs), so that the Monarch Documentation can equally cover all Monarch products and does not give particular emphasis on any one specific product.
